### ISSUE TITLE
Кейс для констант

### ISSUE THREAD

**Issue by PopovWebdelo** [zhashkevych/todo-app#1]
https://github.com/zhashkevych/todo-app/blob/f6d2291990bba68b1ba3475086a0f04b17272921/pkg/service/auth.go#L13

Здравствуйте.
https://www.golangprograms.com/go-language/constants.html

Согласно конвенции константы желательно описывать в верхнем регистре.
У Вас, почему-то, в нижнем. Это ошибка или конвенция изменилась? 
Заранее, спасибо.

**Comment by zhashkevych** [comment]
Андрей, здравствуйте!

Если обратиться к стандартной библиотеке Go, мы можем увидеть следующий формат для констант:
- http.StatusOK (из "net/http")
- time.UnixDate (их "time")

К константам применяются такие же правила регистра, как и другим сущностям программы. Если имя константы начинается с нижнего регистра, она не экспортируема. Поэтому, я использую стандартный формат записи camelCase и записываю константы с нижнего регистра.

На счет конвенций, подобной информации нигде кроме этой ссылки я не находил.
